# Generated by Django 4.2.11 on 2024-04-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_certificate_filmwork_file_path'),
    ]

        # ...
    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE "content"."genre_film_work" 
                ADD CONSTRAINT "genre_film_work_film_work_id_genre_id_uniq" 
                UNIQUE ("film_work_id", "genre_id");
            """,
            reverse_sql='ALTER TABLE "content"."genre_film_work" DROP CONSTRAINT genre_film_work_film_work_id_genre_id_uniq',
        )
    ]
